export const COVIDOCCUR_LIST_SUCCESS = "COVIDOCCUR_LIST_SUCCESS";
export const COVIDOCCUR_LIST_REQUEST = "COVIDOCCUR_LIST_REQUEST";
export const COVIDOCCUR_LIST_FAIL = "COVIDOCCUR_LIST_FAIL";

export const COVIDGENDER_LIST_SUCCESS = "COVIDGENDER_LIST_SUCCESS";
export const COVIDGENDER_LIST_REQUEST = "COVIDGENDER_LIST_REQUEST";
export const COVIDGENDER_LIST_FAIL = "COVIDGENDER_LIST_FAIL";
